---
# tasks file for Ansible-LinuxCommon
- name: Change Host Name
  hostname:
    name: "{{ inventory_hostname_short }}"
  when: LC_CHANGE_HOSTNAME

- name: Replace Hosts File
  template:
    src: "templates/etc/hosts.j2"
    dest: "/etc/hosts"
  when: LC_CHANGE_HOSTNAME

- name: Change System Timezone
  timezone:
    name: "{{ LC_TIMEZONE }}"
  when: LC_CHANGE_TIMEZONE


- name: Setup Official Package Repositories
  template:
    src: "templates/etc/apt/{{ ansible_distribution }}.sources.list.j2"
    dest: "/etc/apt/sources.list"
  when: (ansible_os_family == 'Debian') and (LC_CHANGES_APT_DEFAULT_SOURCES_LIST)

- name: Generate Locales
  debconf:
    name: "locales"
    question: "locales/locales_to_be_generated"
    value: "{{ LC_LOCALES | join(',') }}"
    vtype: multiselect
  when: (LC_SET_LOCALES) and (ansible_os_family == 'Debian')

- name: Set Default Locale to {{ LC_DEFAULT_LOCALE }}
  debconf:
    name: "locales"
    question: "locales/default_environment_locale"
    value: "{{ LC_DEFAULT_LOCALE }}"
    vtype: select
  when: (LC_SET_LOCALES) and (ansible_os_family == 'Debian')

- name: Ensure locales Package is Installed
  apt:
    name: "locales"
    state: present
    update_cache: yes
  when: (LC_SET_LOCALES) and (ansible_os_family == 'Debian')

- name: Set debconf Values
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ LC_DEBCONF_VALUES }}"
  when: (LC_SET_DEBCONF_VALUES) and (ansible_os_family == 'Debian')

- name: Replace bashrc
  copy:
    src: "files/etc/bash.bashrc"
    dest: "/etc/bash.bashrc"
  when: (ansible_os_family == 'Debian') and (LC_MODIFY_SYSTEM_SHELL_ENV)

- name: Replace Skeleton profile
  copy:
    src: "files/root/.profile"
    dest: "/etc/skel/.profile"
    owner: "root"
    group: "root"
  when: (ansible_os_family == 'Debian') and (LC_MODIFY_SKEL)

- name: Replace root profile
  copy:
    src: "files/root/.profile"
    dest: "/root/.profile"
    owner: "root"
    group: "root"
  when: (ansible_os_family == 'Debian') and (LC_MODIFY_ROOT_SHELL_ENV)

- name: Replace User profile
  copy:
    src: "files/home/user/.profile"
    dest: "/home/{{ ansible_user_id }}/.profile"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  when: (ansible_os_family == 'Debian') and (LC_MODIFY_USER_SHELL_ENV)

- name: Setup Official Package Repositories
  template:
    src: "templates/etc/apt/{{ ansible_distribution }}.sources.list.j2"
    dest: "/etc/apt/sources.list"
  when: (ansible_os_family == 'Debian') and (LC_CHANGES_APT_DEFAULT_SOURCES_LIST)

- name: Setup 3rd Party Package Repositories
  template:
    src: "templates/etc/apt/sources.list.d/3rd_party.list.j2"
    dest: "/etc/apt/sources.list.d/{{ item.NAME }}.list"
  with_items: "{{ LC_THIRD_PARTY_REPOS }}"
  when: (LC_SETUP_THIRD_PARTY_REPOS) and (ansible_distribution == 'Debian')

- name: Add 3rd Party Repository Keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ LC_THIRD_PARTY_REPOS_KEYS }}"
  when: (LC_SETUP_THIRD_PARTY_REPOS) and (ansible_distribution == 'Debian')

- name: Install Updates
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Remove Exim
  apt:
    name: "{{ lc_exim_packages }}"
    state: absent
    purge: yes
  when: ansible_os_family == 'Debian'

- name: Install Packages
  apt:
    pkg: "{{ lc_basic_packages + LC_EXTRA_PACKAGES }}"
    state: present
    update_cache: yes
  when: (LC_INSTALL_PACKAGES) and (ansible_os_family == 'Debian')

- name: Install libpam-systemd (for Debian Jessie)
  apt:
    name: "libpam-systemd"
    state: present
    update_cache: yes
  when: (LC_INSTALL_PACKAGES) and (ansible_os_family == 'Debian') and (ansible_distribution_release == 'jessie')

- name: Install sudo
  apt:
    name: "sudo"
    state: present
    update_cache: yes
  when: (ansible_os_family == 'Debian') and (LC_SETUP_SUDO)

- name: Configure sudo Group Login Without Password
  template:
    src: "templates/etc/sudoers.d/95-sudo-group.j2"
    dest: "/etc/sudoers.d/95-sudo-group"
  when: (ansible_os_family == 'Debian') and (LC_SETUP_SUDO)

- name: Add User {{ ansible_user_id }} to sudo Group
  user:
    name: '{{ ansible_user_id }}'
    groups: "sudo"
    append: yes
  when: (ansible_os_family == 'Debian') and (LC_SETUP_SUDO)

- name: Configure vim Editor
  copy:
    src: "files/etc/vim/vimrc.local"
    dest: "/etc/vim/vimrc.local"
  when: (ansible_os_family == 'Debian')

- name: Modify Kernel Parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    reload: yes
  with_items: "{{ LC_KERNEL_PARAMETERS }}"
  when: LC_SET_KERNEL_PARAMETERS

- name: Modify Cloud-Init Configuration to Preserve Hostname
  copy:
    src: "files/etc/cloud/cloud.cfg.d/99_preserve_hostname.cfg"
    dest: "/etc/cloud/cloud.cfg.d/99_preserve_hostname.cfg"
  when: LC_CLOUD_INIT_PRESERVE_HOSTNAME

- name: Modify Cloud-Init Configuration to not Manage /etc/hosts
  copy:
    src: "files/etc/cloud/cloud.cfg.d/99_manage_etc_hosts.cfg"
    dest: "/etc/cloud/cloud.cfg.d/99_manage_etc_hosts.cfg"
  when: LC_CLOUD_INIT_PRESERVE_HOSTNAME

- name: Modify Cloud-Init Configuration to not Manage /etc/apt/sources.list
  copy:
    src: "files/etc/cloud/cloud.cfg.d/99_manage_etc_hosts.cfg"
    dest: "/etc/cloud/cloud.cfg.d/99_manage_etc_hosts.cfg"
  when: LC_CLOUD_INIT_PRESERVE_SOURCES_LIST

- name: Reboot
  shell: sleep 2 && shutdown -r now "Rebooting..."
  async: 1
  poll: 0
  ignore_errors: True
  when: LC_REBOOT

- name: Wait for Server to Reboot
  become: False
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ LC_SSH_PORT }}"
    state: started
    search_regex: OpenSSH
    delay: 10
    timeout: "{{ LC_REBOOT_TIMEOUT }}"
  vars:
    ansible_connection: local
  when: LC_REBOOT
